/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductDTO { 
    id?: number;
    productType?: ProductDTO.ProductTypeEnum;
    title?: string;
    price?: number;
    shelfPrice?: number;
}
export namespace ProductDTO {
    export type ProductTypeEnum = 'BOOK' | 'ENTERTAINMENT' | 'FOOD' | 'PERFUME' | 'MEDICINE';
    export const ProductTypeEnum = {
        Book: 'BOOK' as ProductTypeEnum,
        Entertainment: 'ENTERTAINMENT' as ProductTypeEnum,
        Food: 'FOOD' as ProductTypeEnum,
        Perfume: 'PERFUME' as ProductTypeEnum,
        Medicine: 'MEDICINE' as ProductTypeEnum
    };
}


